version: 2
jobs:
  lint:
    working_directory: ~/zombiesurvival
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          name: install-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-dependencies
          command: npm install
      - run:
          name: lint
          command: npm run lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint